# mac.yml
- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - name: Get number of CPU cores
      command: sysctl -n hw.ncpu
      register: nproc_output
      changed_when: false
      tags:
        - install
        - ffmpeg
        - neovim

    - include_tasks: tasks/mac-core-setup.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/mac-zsh-setup.yml
    - include_tasks: tasks/tmux-setup.yml
    - include_tasks: tasks/mac-node-setup.yml
    - include_tasks: tasks/python-setup.yml
    - include_tasks: tasks/mac-neovim-setup.yml
    - include_tasks: tasks/mac-ffmpeg-setup.yml
    - include_tasks: tasks/mac-docker-setup.yml
    - include_tasks: tasks/mac-productivity-tools.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/dotfiles-setup.yml