- name: Create personal gitconfig
  copy:
    content: |
      [user]
          email = jainishsavalia@gmail.com
          name = Jainish Savalia
    dest: "/home/jainish/.gitconfig-personal"
    mode: "0644"
  tags:
    - git-personal
- name: Create Genuin gitconfig
  copy:
    content: |
      [user]
          email = jainish@begenuin.com
          name = Jainish Savalia
    dest: "/home/jainish/.gitconfig-genuin"
    mode: "0644"
  tags:
    - git-genuin
- name: Configure global gitconfig with includes
  copy:
    content: |
      [includeIf "gitdir:~/personal/"]
          path = ~/.gitconfig-personal
      [includeIf "gitdir:~/work/"]
          path = ~/.gitconfig-genuin
    dest: "/home/jainish/.gitconfig"
    mode: "0644"
  tags:
    - git-personal
    - git-genuin