- name: Create personal gitconfig
  copy:
    content: |
      [user]
          email = jainishsavalia@gmail.com
          name = Jainish Savalia
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig-personal"
    mode: "0644"
  tags:
    - git-personal
- name: Create Work gitconfig
  copy:
    content: |
      [user]
          email = jainish@work.com
          name = Jainish Savalia
    dest: "/home/jainish/.gitconfig-work"
    mode: "0644"
  tags:
    - git-work
- name: Configure global gitconfig with includes
  copy:
    content: |
      [includeIf "gitdir:~/personal/"]
          path = ~/.gitconfig-personal
      [includeIf "gitdir:~/work/"]
          path = ~/.gitconfig-work
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    mode: "0644"
  tags:
    - git-personal
    - git-work
