# tasks/neovim-setup.yml
- name: Remove old neovim build directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/neovim"
    state: absent
  tags:
    - install
    - neovim

- name: Clone Neovim repository
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j{{ nproc_output.stdout }}"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim

- name: Install Neovim plugin development dependencies
  become: true
  apt:
    name:
      - luarocks
  tags:
    - install
    - neovim

- name: Install luacheck for Neovim linting
  become: true
  shell: luarocks install luacheck
  tags:
    - install
    - neovim
