# tasks/ssh.yml
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: '0700'
  tags:
    - dotfiles
    - install
    - ssh

